name: Latest Medium blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '30 11 * * Tue' # Runs every Tuesday at 11:30am
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest Medium blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "MEDIUM"
          feed_list: "https://medium.com/feed/@branden-hernandez"
          max_post_count: 3
